name: mix dialyzer --plt
description: "Build the Dialyzer PLT cache (with cache)"
inputs:
  compile:
    description: "Wether or not to compile the app before hand"
    required: false
    default: "true"
  erlang-version:
    description: "Erlang version"
    required: true
    default: "25.3"
  elixir-version:
    description: "Elixir version"
    required: true
    default: "1.14"
  oban-fingerprint:
    description: "Oban fingerprint"
    required: false
    default: ""
  oban-license:
    description: "Oban license"
    required: false
    default: ""
  mix-env:
    description: "The mix environment to use"
    required: true
  plt-path:
    description: "The path within the workspace where the PLT files should be stored"
    required: false
    default: "priv/plts"
  git-token:
    required: false
    default: ${{ github.token }}
    description: "A Github access token for checking out git-based dependencies."
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
  use-cache:
    description: "Use caches?"
    required: false
    default: "true"
  cache-prefix:
    description: "Optional prefix for the cache key"
    required: false
    default: "cache"
runs:
  using: "composite"
  steps:
    - uses: zoonect/github-ops/actions/mix-compile@main
      with:
        erlang-version: ${{ inputs.erlang-version }}
        elixir-version: ${{ inputs.elixir-version }}
        oban-fingerprint: ${{ inputs.oban-fingerprint }}
        oban-license: ${{ inputs.oban-license }}
        mix-env: ${{ inputs.mix-env }}
        git-token: ${{ inputs.git-token }}
        working-directory: ${{ inputs.working-directory }}
        use-cache: ${{ inputs.use-cache }}
        cache-prefix: ${{ inputs.cache-prefix }}
      if: ${{inputs.compile}}
    - name: Retrieve PLT Cache
      id: plt_cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.plt-path }}
        key: ${{ inputs.cache-prefix }}-plt-${{ inputs.mix-env }}-${{ runner.os }}-${{ runner.arch }}-${{ inputs.erlang-version }}-${{ inputs.elixir-version }}-${{ hashFiles(format('{0}{1}', inputs.working-directory, '/mix.lock')) }}
      if: ${{ inputs.use-cache == 'true' }}
    - name: Create PLTs
      run: |
        mkdir -p ${{ inputs.plt-path }}
        mix dialyzer --plt
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
      if: steps.plt_cache.outputs.cache-hit != 'true'
