name: mix compile
description: "Run `mix compile` with a build cache"
inputs:
  erlang-version:
    description: "Erlang version"
    required: true
    default: "25.3"
  elixir-version:
    description: "Elixir version"
    required: true
    default: "1.14"
  oban-fingerprint:
    description: "Oban fingerprint"
    required: false
    default: ""
  oban-license:
    description: "Oban license"
    required: false
    default: ""
  mix-env:
    description: "The Mix environment to compile within"
    required: true
  git-token:
    required: false
    default: ${{ github.token }}
    description: "A Github access token for checking out git-based dependencies."
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
  use-cache:
    description: "Use caches?"
    required: false
    default: "true"
  cache-prefix:
    description: "Optional prefix for the cache key"
    required: false
    default: "cache"
  compile-assets:
    description: "Wether or not to compile the app assets"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: zoonect/github-ops/actions/mix-deps-get@main
      with:
        erlang-version: ${{ inputs.erlang-version }}
        elixir-version: ${{ inputs.elixir-version }}
        oban-fingerprint: ${{ inputs.oban-fingerprint }}
        oban-license: ${{ inputs.oban-license }}
        git-token: ${{ inputs.git-token }}
        working-directory: ${{ inputs.working-directory }}
        use-cache: ${{ inputs.use-cache }}
        cache-prefix: ${{ inputs.cache-prefix }}
    - name: Retrieve Build Cache
      id: build_cache
      uses: actions/cache@v3
      if: ${{ inputs.use-cache == 'true' }}
      with:
        path: ${{ inputs.working-directory }}/_build
        key: ${{ inputs.cache-prefix}}-build-${{ inputs.mix-env }}-${{ runner.os }}-${{ runner.arch }}-${{ inputs.erlang-version }}-${{ inputs.elixir-version }}-${{ hashFiles(format('{0}{1}', inputs.working-directory, '/mix.lock')) }}
    - run: mix deps.compile
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
    - run: mix compile
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
    - run: mix assets.setup
      if: ${{ inputs.compile-assets == 'true' }}
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
    - run: mix assets.deploy
      if: ${{ inputs.compile-assets == 'true' }}
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
